# Generated by Django 5.0.7 on 2024-07-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('contact_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('website_url', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=75)),
                ('client_street_address', models.CharField(max_length=75)),
                ('client_city', models.CharField(max_length=50)),
                ('client_state', models.CharField(max_length=2)),
                ('client_zip_code', models.CharField(max_length=10)),
                ('event_manager_name', models.CharField(max_length=75)),
                ('date_first_contacted', models.DateField()),
                ('date_last_contacted', models.DateField()),
                ('preferred_event_date', models.DateField()),
                ('actual_event_date', models.DateField()),
                ('band', models.CharField(max_length=75)),
                ('florist', models.CharField(max_length=75)),
                ('caterer', models.CharField(max_length=75)),
                ('notes', models.TextField()),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.venue')),
            ],
        ),
    ]
