# Generated by Django 5.0.7 on 2024-07-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('contact_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('website_url', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterer_name', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('contact_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('website_url', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('florist_name', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('contact_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('website_url', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.band'),
        ),
        migrations.AlterField(
            model_name='event',
            name='caterer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.caterer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='florist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.florist'),
        ),
    ]
