# Generated by Django 5.0.7 on 2024-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_band_caterer_florist_alter_event_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='caterer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='florist',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
