# Generated by Django 5.0.7 on 2024-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0003_alter_band_notes_alter_caterer_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='caterer',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='florist',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
