# Generated by Django 5.0.7 on 2024-07-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_alter_band_website_url_alter_caterer_website_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.band'),
        ),
        migrations.AlterField(
            model_name='event',
            name='caterer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.caterer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='florist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.florist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.venue'),
        ),
    ]
