# Generated by Django 5.0.7 on 2024-07-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0005_alter_event_band_alter_event_caterer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client_email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='caterer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
