# Generated by Django 5.0.7 on 2024-07-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0006_event_client_email_address_event_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actual_event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_last_contacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='preferred_event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
